name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ 

      - name: Build and Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          cd googletest
          cmake -B build -S .
          cmake --build build
          sudo cmake --install build
          cd ..
      
      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run Tests
        run: |
          cd build
          ./calculator_test
