name: Cppcheck Static Analysis

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Run cppcheck
        run: run: cppcheck --enable=all --inconclusive --quiet --error-exitcode=1 --suppress=missingInclude --suppress=missingIncludeSystem .



